-- Add is_signed_up_for_red_bull to profiles table
ALTER TABLE public.profiles
ADD COLUMN is_signed_up_for_red_bull BOOLEAN DEFAULT FALSE;

-- Create redbull_submissions table
CREATE TABLE IF NOT EXISTS public.redbull_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS for the new table
ALTER TABLE public.redbull_submissions ENABLE ROW LEVEL SECURITY;

-- RLS policies for redbull_submissions
CREATE POLICY "Users can insert their own submission"
ON public.redbull_submissions
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own submission"
ON public.redbull_submissions
FOR SELECT USING (auth.uid() = user_id);
